name: Build and Deploy Java Maven Project

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Build Java Maven project
      run: mvn clean install -f Mangata_back_clean/pom.xml

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Mangata_back_clean/target  # Caminho para o diretório de saída dos artefatos de construção do Maven
        publish_branch: gh-pages  # Branch para implantar (você pode personalizar)
        publish_repo: https://github.com/izabely-furtado/Mangata_back_clean.git  # URL do repositório de destino do GitHub Pages

    - name: Cleanup
      run: rm -rf Mangata_back_clean/target  # Limpar os artefatos de construção após a implantação
